### ISSUE TITLE
AttributeError: 'Adam' object has no attribute 'compute_gradients'

### ISSUE THREAD

**Issue by 92berra** [92berra/Decompose#2]
### Problem
- Error while changing tensorflow version from 1.13 to 2.16
- model.py > create_model

### Error Message 

```
Traceback (most recent call last):
  File "/Users/berra/Documents/workspace/Decompose/main.py", line 284, in <module>
    main()
  File "/Users/berra/Documents/workspace/Decompose/main.py", line 92, in main
    model = create_model(examples.src_font, examples.tgt_font, examples.tgt_1stSpt, examples.tgt_2ndSpt, examples.tgt_3rdSpt, \
  File "/Users/berra/Documents/workspace/Decompose/model.py", line 334, in create_model
    gen_grads_and_vars = gen_optim.compute_gradients(gen_loss, var_list=gen_tvars)
AttributeError: 'Adam' object has no attribute 'compute_gradients'
```

**Comment by 92berra** [comment]
Tensorflow 2.6, Adam object does not provide a compute_gradients method. So, correct the error by adding the code below to optimize the slope.

```
with tf.GradientTape() as tape:
  discrim_grads_and_vars = tape.gradient(discrim_loss, discrim_tvars)
```
